
namespace LE {
    public enum PACKET_COMMAND {
        PACKET_COMMAND_ID_AUTH = 0x1,
        PACKET_COMMAND_ID_STATUS = 0x02,
        PACKET_COMMAND_ID_PRES = 0x03,
        PACKET_COMMAND_ID_TOKEN_REDEEM = 0x04,
        PACKET_COMMAND_ID_TOKEN_CHECK = 0x05,
        PACKET_COMMAND_ID_XKE = 0x06,
        PACKET_COMMAND_ID_TIME = 0x07,
        PACKET_COMMAND_ID_SECURITY = 0x08,
        PACKET_COMMAND_ID_XSC = 0x09,
        PACKET_COMMAND_ID_OFFSETS = 0x10,
        PACKET_COMMAND_ID_CE = 0x11,
        PACKET_COMMAND_ID_CPI = 0x12,
        PACKET_COMMAND_ID_SETTINGS = 0x13
    }
    
}